# Generated by Django 2.2.5 on 2019-09-04 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Castle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('castle_name', models.CharField(max_length=40)),
                ('hero_attack_bonus', models.IntegerField()),
                ('hero_defence_bonus', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('lvl', models.CharField(max_length=8)),
                ('attack', models.IntegerField()),
                ('defence', models.IntegerField()),
                ('min_dmg', models.IntegerField()),
                ('max_dmg', models.IntegerField()),
                ('health', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('growth', models.IntegerField()),
                ('fight_value', models.IntegerField()),
                ('AI_value', models.IntegerField()),
                ('special_abilities', models.CharField(max_length=512)),
                ('castle_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creatures_ranking.Castle')),
            ],
        ),
    ]
