# Generated by Django 2.2.5 on 2019-10-16 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creatures_ranking', '0002_auto_20190906_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='vote_minus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='creature2', to='creatures_ranking.Creature'),
        ),
        migrations.AlterField(
            model_name='votes',
            name='vote_plus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='creature1', to='creatures_ranking.Creature'),
        ),
    ]
